version: "3.2"
services:
  blipp:
    image: baljan/blipp
    build: https://github.com/Baljan/baljans-balla-blipp.git
    env_file: .env.docker
    environment:
      - NEXT_PUBLIC_BLIPP_API="http://localhost:8000"
    ports:
      - "8001:80"

  celery-worker:
    image: baljan/cafesys
    build:
      context: .
    env_file: .env.docker
    command: /app/bin/run-celery-worker
    links:
      - redis
      - postgres

  django:
    image: baljan/cafesys
    build:
      context: .
    env_file: .env.docker
    command: /app/bin/run-django
    ports:
      - "8000:8000"
    links:
      - redis
      - postgres
    volumes:
      # Mount static files after build
      - ./cafesys/baljan/static:/app/cafesys/baljan/static

  postgres:
    image: postgres:15.7-alpine
    env_file: .env.docker
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      # This gives us a Postgres server listening on the host as well. This can be useful for development outside the
      # Docker environment.
      - 5432:5432

  redis:
    image: redis:3-alpine
    env_file: .env.docker
    ports:
      # This gives us a Redis server listening on the host as well. This can be useful for development outside the
      # Docker environment.
      - 6379:6379
