# -*- coding: utf-8 -*-
from . import *

DEBUG = env.bool('DJANGO_DEBUG', default=False)
TEMPLATE_DEBUG = DEBUG

SECRET_KEY = env.str('DJANGO_SECRET_KEY')

_EMAIL_CONFIG = env.email_url('DJANGO_EMAIL_URL')
EMAIL_BACKEND = _EMAIL_CONFIG.get('EMAIL_BACKEND')
EMAIL_HOST = _EMAIL_CONFIG.get('EMAIL_HOST')
EMAIL_HOST_USER = _EMAIL_CONFIG.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = _EMAIL_CONFIG.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = _EMAIL_CONFIG.get('EMAIL_PORT')
EMAIL_USE_TLS = _EMAIL_CONFIG.get('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = CONTACT_EMAIL

SERVE_MEDIA = False

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
