embed_assets: datauri
javascript_compressor: closure
compress_assets: off

javascripts:
    workspace:
        - public/js/jquery-1.4.2.min.js
        - public/js/jquery.plugins.js
        - public/js/jquery-ui-*.min.js
        - public/js/uni-form.jquery.js
        - public/js/baljan.js
    nomcom:
        - public/bootstrap/js/bootstrap-dropdown.js
        - public/bootstrap/js/bootstrap-twipsy.js
        - public/bootstrap/js/bootstrap-scrollspy.js

stylesheets:
    workspace:
        - public/uni_form/uni-form.css
        - public/uni_form/default.uni-form.css
        - public/css/960.css
        - public/css/flick/jquery-ui-1.8.2.custom.css
        - public/css/site_base.css
        - public/css/baljan.css
    nomcom:
        - public/bootstrap/bootstrap.min.css
        - public/nomcom.css
