embed_assets: datauri
javascript_compressor: closure
compress_assets: on

javascripts:
    workspace:
        - public/js/jquery-1.4.2.min.js
        - public/pinax/js/base.js
        - public/js/jquery.plugins.js
        - public/js/jquery-ui-*.min.js
        - public/js/uni-form.jquery.js
        - public/js/baljan.js

stylesheets:
    workspace:
        - public/pinax/css/facebox.css
        - public/pinax/css/announcements.css
        - public/pinax/css/accounts.css
        - public/uni_form/uni-form.css
        - public/css/960.css
        - public/css/flick/jquery-ui-1.8.2.custom.css
        - public/css/site_base.css
        - public/css/baljan.css
