# Requires short (https://docs.koki.io/short/). See motivation for usage in their documentation.
# Apply using: short -k -f kube.short.yaml | sed 's/selector: {}//g' | kubectl apply -f -
# (the sed is needed to fix a bug with the short/GKE combination)

namespace:
  name: baljan
---
deployment:
  version: extensions/v1beta1
  name: baljan-blipp
  namespace: baljan
  labels:
    run: baljan-blipp
  replicas: 1
  selector:
    run: baljan-blipp
  containers:
  - name: baljan-blipp
    image: gcr.io/sektionscafe-baljan/blipp:latest
    pull: always
    expose:
    - 80
    env:
    - from: config:baljan-config
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=sektionscafe-baljan:europe-west1:baljan-db=tcp:5432",
              "-credential_file=/secrets/cloudsql/Baljan-6a5cb68f99a2.json"]
    volume:
    - mount: /secrets/cloudsql
      store: cloudsql-instance-credentials:ro
  volumes:
    cloudsql-instance-credentials: secret:cloudsql-instance-credentials
---
deployment:
  version: extensions/v1beta1
  name: cafesys-celery-beat
  namespace: baljan
  labels:
    run: cafesys-celery-beat
  replicas: 1
  selector:
    run: cafesys-celery-beat
  containers:
  - name: cafesys-celery-beat
    image: gcr.io/sektionscafe-baljan/cafesys:latest
    pull: always
    command:
    - /app/bin/run-celery-beat
    expose:
    - 80
    env:
    - from: config:baljan-config
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=sektionscafe-baljan:europe-west1:baljan-db=tcp:3306",
              "-credential_file=/secrets/cloudsql/Baljan-6a5cb68f99a2.json"]
    volume:
    - mount: /secrets/cloudsql
      store: cloudsql-instance-credentials:ro
  volumes:
    cloudsql-instance-credentials: secret:cloudsql-instance-credentials
---
deployment:
  version: extensions/v1beta1
  name: cafesys-celery-worker
  namespace: baljan
  labels:
    run: cafesys-celery-worker
  replicas: 1
  selector:
    run: cafesys-celery-worker
  containers:
  - name: cafesys-celery-worker
    image: gcr.io/sektionscafe-baljan/cafesys:latest
    pull: always
    command:
    - /app/bin/run-celery-worker
    expose:
    - 80
    env:
    - from: config:baljan-config
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=sektionscafe-baljan:europe-west1:baljan-db=tcp:3306",
              "-credential_file=/secrets/cloudsql/Baljan-6a5cb68f99a2.json"]
    volume:
    - mount: /secrets/cloudsql
      store: cloudsql-instance-credentials:ro
  volumes:
    cloudsql-instance-credentials: secret:cloudsql-instance-credentials
---
deployment:
  version: extensions/v1beta1
  name: cafesys-django
  namespace: baljan
  labels:
      run: cafesys-django
  replicas: 1
  selector:
    run: cafesys-django
  containers:
  - name: cafesys-django
    image: gcr.io/sektionscafe-baljan/cafesys:latest
    pull: always
    expose:
    - 80
    env:
    - from: config:baljan-config
    - VIRTUAL_HOST=baljan.org,beta.baljan.org,www.baljan.org
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=sektionscafe-baljan:europe-west1:baljan-db=tcp:3306",
              "-credential_file=/secrets/cloudsql/Baljan-6a5cb68f99a2.json"]
    volume:
    - mount: /secrets/cloudsql
      store: cloudsql-instance-credentials:ro
  volumes:
    cloudsql-instance-credentials: secret:cloudsql-instance-credentials
---
deployment:
  version: extensions/v1beta1
  name: postgres
  namespace: baljan
  labels:
    run: postgres
  replicas: 1
  selector:
    run: postgres
  containers:
  - name: postgres
    image: postgres:9.6-alpine
    pull: if-not-present
    expose:
    - 5432
    env:
    - from: config:baljan-config
---
deployment:
  version: extensions/v1beta1
  name: redis
  namespace: baljan
  labels:
    run: redis
  replicas: 1
  selector:
    run: redis
  containers:
  - name: redis
    image: redis:3-alpine
    pull: if-not-present
    expose:
    - 6379
    env:
    - from: config:baljan-config
---
service:
  version: v1
  name: redis
  namespace: baljan
  type: cluster-ip
  port: tcp://6379
  selector:
    run: redis
---
service:
  version: v1
  name: postgres
  namespace: baljan
  type: cluster-ip
  port: tcp://5432
  selector:
    run: postgres
---
service:
  version: v1
  name: cafesys-django
  namespace: baljan
  type: cluster-ip
  port: tcp://80
  selector:
    run: cafesys-django
---
service:
  version: v1
  name: baljan-blipp
  namespace: baljan
  type: cluster-ip
  port: tcp://80
  selector:
    run: baljan-blipp