# Generated by Django 5.2.1 on 2025-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blippen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[("audio", "Audio"), ("image", "Image")], default="audio"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="priority",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="asset",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="theme",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
