# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sent_to',
        ),
        migrations.RemoveField(
            model_name='joingrouprequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='joingrouprequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fb_access_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friend_profiles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='code_count',
            field=models.PositiveIntegerField(default=16, help_text='multipel av 16 rekommenderas (4x4 på A4-papper), totalt maxvärde är 8000 SEK', verbose_name='code count'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='code_value',
            field=models.PositiveIntegerField(default=300, help_text='maxvärde är 500 SEK', verbose_name='code value'),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='JoinGroupRequest',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
