# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baljan", "0002_auto_20170521_2236"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="good",
            name="img",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="picture",
        ),
    ]
