# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-17 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0006_auto_20180320_1034'),
        ('baljan', '0005_auto_20180307_2022'),
    ]

    operations = [
    ]
