# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baljan", "0007_legalconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_seen_consent",
            field=models.BooleanField(default=False),
        ),
    ]
