# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-03 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0012_auto_20190501_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blippconfiguration',
            options={'verbose_name': 'Blipp-konfiguration', 'verbose_name_plural': 'Blipp-konfigurationer'},
        ),
    ]
