# Generated by Django 2.2.24 on 2021-10-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0015_auto_20190817_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='used by'),
        ),
        migrations.AlterField(
            model_name='blippconfiguration',
            name='good',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='baljan.Good', verbose_name='good'),
        ),
        migrations.AlterField(
            model_name='incomingcallfallback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='legalconsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='mutedconsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='oldcoffeecard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='add_to_group',
            field=models.ForeignKey(blank=True, default=None, help_text='if set, users will be added to this group',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='add to group'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='made_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='made by'),
        ),
        migrations.AlterField(
            model_name='refillseriespdf',
            name='generated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='generated by'),
        ),
    ]
