# Generated by Django 3.2.8 on 2021-11-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0016_auto_20211010_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldcoffeecardset',
            name='made_by',
        ),
        migrations.DeleteModel(
            name='OldCoffeeCard',
        ),
        migrations.DeleteModel(
            name='OldCoffeeCardSet',
        ),
    ]
