# Generated by Django 3.2.12 on 2022-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0018_auto_20211209_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True, help_text='when the object was created', verbose_name='made at')),
                ('phone_number', models.CharField(db_index=True, help_text='Skriv endast siffror och utan landskod. Exempelvis: 0701234567', max_length=10, unique=True, verbose_name='Telefonnummer')),
                ('label', models.CharField(max_length=64, verbose_name='Markering')),
            ],
            options={
                'verbose_name': 'Jourtelefon markering',
                'verbose_name_plural': 'Jourtelefon markeringar',
            },
        ),
        migrations.AlterModelOptions(
            name='incomingcallfallback',
            options={'ordering': ('-priority', 'user__username'), 'verbose_name': 'Styrelsemedlem att ringa', 'verbose_name_plural': 'Jourtelefon reservlista'},
        ),
    ]
