# Generated by Django 3.2.12 on 2022-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0019_auto_20220614_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='blippconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='blippconfiguration',
            name='theme_override',
            field=models.CharField(blank=True, help_text='Skriv namnet på ett tema du vill använda på just denna blipp. Används i undantagsfall, i regel konfigureras teman istället i blippens repo.', max_length=64, verbose_name='Tema'),
        ),
    ]
