# Generated by Django 5.2.1 on 2025-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0020_auto_20220913_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecode',
            name='value',
            field=models.PositiveIntegerField(default=315, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='code_value',
            field=models.PositiveIntegerField(choices=[(105, '105 kr'), (315, '315 kr')], default=0, verbose_name='code value'),
        ),
    ]
