# Generated by Django 5.2.1 on 2025-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0021_alter_balancecode_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'From'), (1, 'Subject')], default=0)),
                ('value', models.CharField(max_length=512, verbose_name='Value')),
            ],
        ),
    ]
