# Generated by Django 5.2.1 on 2025-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0022_supportfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportfilter',
            options={'verbose_name': 'support mail filter', 'verbose_name_plural': 'support mail filter'},
        ),
        migrations.AlterField(
            model_name='supportfilter',
            name='type',
            field=models.IntegerField(choices=[(0, 'From'), (1, 'Subject')], default=0, verbose_name='type of filter'),
        ),
        migrations.AlterField(
            model_name='supportfilter',
            name='value',
            field=models.CharField(max_length=512, verbose_name='value'),
        ),
    ]
