# Generated by Django 5.2.1 on 2025-06-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0022_supportfilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='This should correspond to the Product ID in the Stripe admin', unique=True, verbose_name='product id')),
                ('price_id', models.CharField(editable=False, help_text='This will be filled in by Stripe', verbose_name='price id')),
                ('name', models.CharField(editable=False, verbose_name='name')),
                ('image', models.CharField(verbose_name='image')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True, help_text='when the object was created', verbose_name='made at')),
                ('session_id', models.CharField(unique=True, verbose_name='session id')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Paid'), (1, 'Unpaid')], default=1, verbose_name='status')),
                ('value', models.PositiveSmallIntegerField(verbose_name='value')),
                ('currency', models.CharField(verbose_name='currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baljan.product', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
