# Generated by Django 5.2.1 on 2025-06-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0023_alter_supportfilter_options_alter_supportfilter_type_and_more'),
        ('baljan', '0023_product_purchase'),
    ]

    operations = [
    ]
