# Generated by Django 5.2.1 on 2025-06-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0023_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
