# Generated by Django 5.2.1 on 2025-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0024_merge_20250622_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecode',
            name='value',
            field=models.PositiveIntegerField(default=405, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='refillseries',
            name='code_value',
            field=models.PositiveIntegerField(choices=[(135, '135 kr'), (405, '405 kr')], default=0, verbose_name='code value'),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('available_for_call_duty', 'Available for call duty'), ('free_coffee_unlimited', 'Unlimited free coff ee'), ('free_coffee_with_cooldown', 'Free coffee with cooldown'), ('online_refill', 'Online refill of coffee card balance')), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),

    ]
