# Generated by Django 5.2.1 on 2026-03-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0026_alter_profile_options_wrapped'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS emailconfirmation_emailconfirmation;"),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS emailconfirmation_emailaddress;"
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS notification_noticesetting;"),
        migrations.RunSQL("DROP TABLE IF EXISTS notification_noticequeuebatch;"),
        migrations.RunSQL("DROP TABLE IF EXISTS notification_observeditem;"),
        migrations.RunSQL("DROP TABLE IF EXISTS notification_notice;"),
        migrations.RunSQL("DROP TABLE IF EXISTS notification_noticetype;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_message;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_filtervalue;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_messagecountbyminute;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_messagefiltervalue;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_messageindex;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sentry_groupedmessage;"),
        migrations.RunSQL("DROP TABLE IF EXISTS signup_codes_signupcoderesult;"),
        migrations.RunSQL("DROP TABLE IF EXISTS signup_codes_signupcode;"),
        migrations.RunSQL("DROP TABLE IF EXISTS announcements_announcement;"),
    ]
