# Generated by Django 5.2.1 on 2026-04-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0027_remove_unused_old_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-end'], 'permissions': (('manage_job_openings', 'Can manage job openings'),), 'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
        migrations.AlterField(
            model_name='legalconsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
