# Generated by Django 5.2.1 on 2026-09-20 16:19

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0031_alter_legalconsent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True, help_text='when the object was created', verbose_name='made at')),
                ('orderer', models.CharField(max_length=100, verbose_name='orderer')),
                ('orderer_email', models.EmailField(max_length=254, verbose_name='orderer email')),
                ('orderer_phone', models.CharField(max_length=11, verbose_name='orderer phone number')),
                ('association', models.CharField(max_length=100, verbose_name='association')),
                ('org_number', models.CharField(blank=True, default='', max_length=20, verbose_name='organisation number')),
                ('pickup_name', models.CharField(blank=True, default='', max_length=100, verbose_name='name of person picking up')),
                ('pickup_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email of person picking up')),
                ('pickup_phone', models.CharField(blank=True, default='', max_length=11, verbose_name='phone number of person picking up')),
                ('date', models.DateField(verbose_name='date')),
                ('pickup', models.PositiveSmallIntegerField(choices=[(1, 'Morgon 07:30-08:00'), (2, 'Lunch 12:15-13:00'), (3, 'Eftermiddag 16:15-17:00')], verbose_name='pickup time')),
                ('other', models.TextField(blank=True, default='', verbose_name='other information and allergies')),
                ('displayed_sum', models.CharField(blank=True, default='', max_length=32, verbose_name='sum shown to the orderer')),
                ('items', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='items')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('delivered', 'delivered'), ('invoiced', 'invoiced')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('staff_note', models.TextField(blank=True, default='', help_text='only visible to the board, never sent to the orderer', verbose_name='internal note')),
                ('staff_message', models.TextField(blank=True, default='', help_text='included in the email sent when the order is decided', verbose_name='message to the orderer')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='handled at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_catering_orders', to=settings.AUTH_USER_MODEL, verbose_name='handled by')),
            ],
            options={
                'verbose_name': 'catering order',
                'verbose_name_plural': 'catering orders',
                'ordering': ['-made'],
                'permissions': (('manage_catering_orders', 'Can manage catering orders'),),
            },
        ),
    ]
