# Generated by Django 5.2.1 on 2026-09-25 12:07

from collections import Counter, defaultdict

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prefill_from_shifts(apps, schema_editor):
    """Starts every week that has shifts with the three people who have the
    most on call shifts that week. After this the weeks are edited by hand and
    never follow the shifts again.
    """
    OnCallDuty = apps.get_model("baljan", "OnCallDuty")
    OnCallWeek = apps.get_model("baljan", "OnCallWeek")

    per_week = defaultdict(Counter)
    names = {}
    duties = OnCallDuty.objects.values_list(
        "shift__when", "user_id", "user__first_name", "user__last_name"
    )
    for when, user_id, first_name, last_name in duties.iterator():
        year, week, _ = when.isocalendar()
        per_week[(year, week)][user_id] += 1
        names[user_id] = (first_name, last_name)

    for (year, week), counts in per_week.items():
        top = sorted(counts, key=lambda u: (-counts[u], names[u]))[:3]
        ocw, _ = OnCallWeek.objects.get_or_create(year=year, week=week)
        for field, user_id in zip(("jour_1_id", "jour_2_id", "jour_3_id"), top):
            setattr(ocw, field, user_id)
        ocw.save()


class Migration(migrations.Migration):
    dependencies = [
        ("baljan", "0031_alter_legalconsent_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnCallWeek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "made",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="when the object was created",
                        verbose_name="made at",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="år")),
                ("week", models.PositiveSmallIntegerField(verbose_name="vecka")),
                (
                    "info",
                    models.CharField(blank=True, max_length=100, verbose_name="info"),
                ),
                (
                    "jour_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 1",
                    ),
                ),
                (
                    "jour_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 2",
                    ),
                ),
                (
                    "jour_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "jourvecka",
                "verbose_name_plural": "jourveckor",
                "ordering": ("-year", "-week"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "week"), name="unique_oncallweek"
                    )
                ],
            },
        ),
        migrations.RunPython(prefill_from_shifts, migrations.RunPython.noop),
    ]
