# Generated by Django 5.2.1 on 2026-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0033_catering_order_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Väntar'), ('approved', 'Godkänd'), ('denied', 'Nekad'), ('cancelled', 'Avbeställd'), ('delivered', 'Levererad'), ('invoiced', 'Fakturerad')], db_index=True, default='pending', max_length=16, verbose_name='status'),
        ),
    ]
