# Generated by Django 5.2.1 on 2026-09-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0034_alter_cateringorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringOrderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True, help_text='when the object was created', verbose_name='made at')),
                ('kind', models.CharField(choices=[('approved', 'Godkännande'), ('denied', 'Nekande')], max_length=16, verbose_name='kind')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('to_email', models.EmailField(max_length=254, verbose_name='recipient')),
                ('body', models.TextField(blank=True, default='', help_text='what the board wrote, not the full rendered email', verbose_name='message')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='baljan.cateringorder', verbose_name='catering order')),
            ],
            options={
                'verbose_name': 'sent catering order email',
                'verbose_name_plural': 'sent catering order emails',
                'ordering': ['made'],
            },
        ),
    ]
