# Generated by Django 5.2.1 on 2026-09-22 12:17

import cafesys.baljan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0037_cateringorder_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='handled_by_name',
            field=models.CharField(blank=True, default='', max_length=100, validators=[cafesys.baljan.models.validate_no_control_characters], verbose_name='name of the person who decided'),
        ),
    ]
