# Generated by Django 5.2.1 on 2026-09-22 12:54

import cafesys.baljan.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baljan', '0038_cateringorder_handled_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringOrderStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True, help_text='when the object was created', verbose_name='made at')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('approved', 'Godkänd'), ('denied', 'Nekad'), ('cancelled', 'Avbeställd'), ('delivered', 'Levererad'), ('invoiced', 'Fakturerad')], max_length=16, verbose_name='status')),
                ('by_name', models.CharField(blank=True, default='', max_length=100, validators=[cafesys.baljan.models.validate_no_control_characters], verbose_name='by')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='by account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='baljan.cateringorder', verbose_name='catering order')),
            ],
            options={
                'verbose_name': 'catering order status change',
                'verbose_name_plural': 'catering order status changes',
                'ordering': ['made'],
            },
        ),
    ]
