# Generated by Django 5.2.1 on 2026-09-30 20:24

import cafesys.baljan.models
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baljan", "0040_cateringorderstatuschange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cateringorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Väntar"),
                    ("approved", "Godkänd"),
                    ("denied", "Nekad"),
                    ("cancelled", "Avbeställd"),
                    ("delivered", "Utlämnad"),
                    ("returned", "Återlämnad"),
                    ("invoiced", "Fakturerad"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="cateringorderstatuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Väntar"),
                    ("approved", "Godkänd"),
                    ("denied", "Nekad"),
                    ("cancelled", "Avbeställd"),
                    ("delivered", "Utlämnad"),
                    ("returned", "Återlämnad"),
                    ("invoiced", "Fakturerad"),
                ],
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="CateringHandout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "made",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="when the object was created",
                        verbose_name="made at",
                    ),
                ),
                (
                    "lines",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="lines",
                    ),
                ),
                (
                    "thermoses",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="thermoses",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="committee or other reference",
                    ),
                ),
                (
                    "picked_up_by",
                    models.CharField(
                        max_length=100,
                        validators=[
                            cafesys.baljan.models.validate_no_control_characters
                        ],
                        verbose_name="picked up by",
                    ),
                ),
                (
                    "picked_up_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "jochen_boxes_out",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="jochen boxes handed out"
                    ),
                ),
                (
                    "jochen_boxes_returned",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="jochen boxes returned"
                    ),
                ),
                (
                    "return_by",
                    models.DateField(blank=True, null=True, verbose_name="return by"),
                ),
                (
                    "handed_out_by",
                    models.CharField(
                        max_length=100,
                        validators=[
                            cafesys.baljan.models.validate_no_control_characters
                        ],
                        verbose_name="handed out by",
                    ),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True, default="", verbose_name="other information"
                    ),
                ),
                (
                    "return_note",
                    models.TextField(
                        blank=True, default="", verbose_name="note on return"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handout",
                        to="baljan.cateringorder",
                        verbose_name="catering order",
                    ),
                ),
            ],
            options={
                "verbose_name": "catering handout",
                "verbose_name_plural": "catering handouts",
            },
        ),
    ]
