# Generated by Django 5.2.1 on 2026-09-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baljan", "0041_catering_handout_and_returned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnCallWeek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "made",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="when the object was created",
                        verbose_name="made at",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="år")),
                ("week", models.PositiveSmallIntegerField(verbose_name="vecka")),
                (
                    "info",
                    models.CharField(blank=True, max_length=100, verbose_name="info"),
                ),
                (
                    "jour_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 1",
                    ),
                ),
                (
                    "jour_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 2",
                    ),
                ),
                (
                    "jour_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jour 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "jourvecka",
                "verbose_name_plural": "jourveckor",
                "ordering": ("-year", "-week"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "week"), name="unique_oncallweek"
                    )
                ],
            },
        ),
    ]
