# Generated by Django 5.2.1 on 2026-09-25 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baljan", "0042_oncallweek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oncallweek",
            name="info",
        ),
    ]
